org: orgpavca
app: todolist
service: toDoList

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  endpointType: PRIVATE
  name: aws
  runtime: python3.12
  region: eu-west-3

  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource: execute-api:/*
        Condition:
          StringEquals:
            aws:SourceVpce: !Ref ExecuteApiEndpoint

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [MyQueue, Arn]
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [MyQueue, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    QUEUE_URL: !Ref MyQueue

functions:
  producer:
    handler: producer.handler # required, handler set in AWS Lambda
    name: ${sls:stage}-Producer # optional, Deployed Lambda name
    description: Push in queue
    runtime: python3.11 # optional overwrite, default is provider runtime
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
    vpc:
      securityGroupIds:
        - !Ref InstanceSecurityGroup
      subnetIds:
        - !Ref PrivateSubnetA
    events:
      - http:
          path: /tasks
          method: post

  consumer:
    handler: consumer.handler # required, handler set in AWS Lambda
    name: ${sls:stage}-consumer # optional, Deployed Lambda name
    description: Consume from queue
    runtime: python3.11 # optional overwrite, default is provider runtime
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
    vpc:
      securityGroupIds:
        - !Ref InstanceSecurityGroup
      subnetIds:
        - !Ref PrivateSubnetA
    events:
      - sqs:
          arn: !GetAtt MyQueue.Arn
          batchSize: 1               
          functionResponseType: ReportBatchItemFailures

resources:
  Parameters:
    VpcCidr:
      Type: String
      Default: 10.0.0.0/16
    PrivateSubnetCidr:
      Type: String
      Default: 10.0.1.0/24
    PrivateSubnetCidrB:
      Type: String
      Default: 10.0.2.0/24
    InstanceType:
      Type: String
      Default: t3.micro
      AllowedValues: [t3.micro, t3.small, t3.medium]
      Description: EC2 type
    LatestAmiId:
      Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
      Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64


  Resources:

    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcCidr
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: !Sub "${AWS::StackName}-vpc"

    PrivateSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: !Ref PrivateSubnetCidr
        AvailabilityZone: eu-west-3a
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: !Sub "subnet-A"

    PrivateSubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: !Ref PrivateSubnetCidrB
        AvailabilityZone: eu-west-3b
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: !Sub "subnet-B"

    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: todolist-queue-${sls:stage}
        VisibilityTimeout: 30


    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableName}

    SqsEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        VpcId: !Ref Vpc
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.sqs"
        VpcEndpointType: Interface
        PrivateDnsEnabled: true
        SubnetIds:
          - !Ref PrivateSubnetA
        SecurityGroupIds:
          - !Ref EndpointSecurityGroup

    EndpointSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: HTTPS de la Lambda catre endpoint
        VpcId: !Ref Vpc
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            SourceSecurityGroupId: !Ref InstanceSecurityGroup

    ExecuteApiEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        VpcId: !Ref Vpc
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.execute-api"
        VpcEndpointType: Interface
        PrivateDnsEnabled: true
        SubnetIds:
          - !Ref PrivateSubnetA
        SecurityGroupIds:
          - !Ref EndpointSecurityGroup

#------------------Instance for testing-----------------
    Eice:
      Type: AWS::EC2::InstanceConnectEndpoint
      Properties:
        SubnetId: !Ref PrivateSubnetA
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        PreserveClientIp: false
        Tags:
          - Key: Name
            Value: !Sub "${AWS::StackName}-eice"

    InstanceA:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: !Ref InstanceType
        ImageId: !Ref LatestAmiId
        SubnetId: !Ref PrivateSubnetA
        # KeyName: !Ref KeyPair
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        Tags:
          - Key: Name
            Value: !Sub "Node-A"

    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SSH - allow
        VpcId: !Ref Vpc
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref VpcCidr
            Description: SSH din EICE
        Tags:
          - Key: Name
            Value: !Sub "${AWS::StackName}-instance-sg"

#------------------Instance for testing-----------------
