org: orgpavca
app: todolist
service: toDoList

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: python3.12
  region: eu-west-3

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [MyQueue, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    QUEUE_URL: !Ref MyQueue

functions:
  producer:
    handler: producer.handler # required, handler set in AWS Lambda
    name: ${sls:stage}-Producer # optional, Deployed Lambda name
    description: Push in queue
    runtime: python3.11 # optional overwrite, default is provider runtime
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
    vpc:
      securityGroupIds:
        - !Ref InstanceSecurityGroup
      subnetIds:
        - !Ref PrivateSubnetA

resources:
  Parameters:
    VpcCidr:
      Type: String
      Default: 10.0.0.0/16
    PrivateSubnetCidr:
      Type: String
      Default: 10.0.1.0/24
    PrivateSubnetCidrB:
      Type: String
      Default: 10.0.2.0/24


  Resources:

    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SSH - allow
        VpcId: !Ref Vpc
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref VpcCidr
            Description: SSH din EICE
        Tags:
          - Key: Name
            Value: !Sub "${AWS::StackName}-instance-sg"

    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcCidr
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: !Sub "${AWS::StackName}-vpc"

    PrivateSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: !Ref PrivateSubnetCidr
        AvailabilityZone: eu-west-3a
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: !Sub "subnet-A"

    PrivateSubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref Vpc
        CidrBlock: !Ref PrivateSubnetCidrB
        AvailabilityZone: eu-west-3b
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: !Sub "subnet-B"

    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: todolist-queue-${sls:stage}
        VisibilityTimeout: 30


    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableName}
